FROM docker-registry.wikimedia.org/dev/bookworm-php85:1.0.0-arm1

RUN apt-get update && apt-get upgrade -yq && apt-get install -yq ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# MediaWiki default settings
COPY ../files/mediawiki-jobrunner/docker/PlatformSettings.php /docker/PlatformSettings.php

WORKDIR "/var/www/html/w"

COPY ../files/mediawiki-jobrunner/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
